### PR TITLE
Misc bugfixes (for 0.2.6 release)

### PR DESCRIPTION
**Pull request by connor4312**
Fixes all the open issues:
 - #42, this was a bug in our code which handles a case that etcd actually [handles for us](https://github.com/coreos/etcd/blob/master/mvcc/watchable_store.go#L122-L128), so 🔥 that
 - #43, a good bit of churn but easy. Just throwing around more args/methods
 - #44, caused by a change in the proto which added a dependency cycle we didn't deal with
 - #45, straightforward
 - #46, straightforward

### CODE REVIEW

**Comment by reptilbud** [comment]
Do you think we will see it merged and published soon ?

**Comment by SimonSchick** [comment]
@connor4312 seems to have a single test case failure.

**Comment by reptilbud** [comment]
Hey there, any news ? Would be great to have this soon else I'll need to use another library

**Comment by connor4312** [comment]
Sorry, an emergency came up, I'll release this as soon as I can

**Pull request merged**
